name: Terraform checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - name: Terraform Format
        run: terraform fmt -check
      - uses: ./.github/actions/hello-world-action
