name: Terraform checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
  build:
    runs-on: self-hosted
    steps:
       - name: Terraform Format
         id: fmt
         run: terraform fmt -check
